### PR TITLE
Fix miseq multiqc file name split

### PR DESCRIPTION
**Pull request by RachelDuffin**
If miseq the flowcell id contains a "-". The multiqc file name is split on "-" to capture the project id but the presense of this extra dash means this is now incorrect. 

Fix takes the html name, reverses it, cuts at "-" and takes the second and third elements after cutting, then reverses these again to give the correct file name (this makes sure that it is always the "-multiqc.html" element being removed regardless of the number of "-" present). Tested on NextSeq and MiSeq project names.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
I can't see any other files in the repo. we'd need to increase the version number in the readme and the json. also correct the readme if required

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-:-MM0xGd927VEInqKbu59:b9cplfb)* status: 0 of 1 files reviewed, all discussions resolved

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MM0z3cu5W_WyQ6cmE4u:-MM0z3cu5W_WyQ6cmE4v:b3kre) ([raw file](https://github.com/moka-guys/dnanexus_upload_multiqc/blob/d8821775c0c77c81f8e505f43ce756f74bb1f40e/README.md#L12)):*
> ```Markdown
> On completion of a sequencing run, this app is run to make multiqc reports available for viewing at [https://genomics.viapath.co.uk/mokaguys/multiqc/]
> 
> ## What inputs are required fix_mulitqc_id_splitfor this app to run?
> ```

?

**Review by RachelDuffin — COMMENTED** [review]
Updated version numbers in the readme and json. 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-:-MM1-gk_5RDHtgjqKBAz:biq4a4z)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MM0z3cu5W_WyQ6cmE4u:-MM10NVY2iI-welkBqju:bj212u7) ([raw file](https://github.com/moka-guys/dnanexus_upload_multiqc/blob/d8821775c0c77c81f8e505f43ce756f74bb1f40e/README.md#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

?
</blockquote></details>

Sorry not sure what happened there, its been removed now.

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MMRSZkf7FAnnK16cLRY:-MMRSZkf7FAnnK16cLRZ:b-e248yd) (no related file):*
Tested on three DNAnexus projects (one of each of WES, Custom Panels, SWIFT). Files were succesfully uploaded to the genomics server, with naming of all three multiqc_data folders on the server now correct. 

---

**Comment by Graeme-Smith** [comment]
*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MMRSZkf7FAnnK16cLRY:-MMV-QWl9-thu4Y8MWJe:bb6ywmx) (no related file):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Tested on three DNAnexus projects (one of each of WES, Custom Panels, SWIFT). Files were succesfully uploaded to the genomics server, with naming of all three multiqc_data folders on the server now correct. 
</blockquote></details>

LGTM

---

**Comment by Graeme-Smith** [comment]
___
*[src/code.sh, line 51 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MMUwGm3B5ojR0--PFwh:-MMUwGm3B5ojR0--PFwi:b-l6wovm) ([raw file](https://github.com/moka-guys/dnanexus_upload_multiqc/blob/b21216b7a2dc055f1c997fe0db9c2ac48884217a/src/code.sh#L51)):*
> ```Shell
> if [[ "$upload_data_files" == "true" ]]; then
>     # capture the project name from the multiqc html name (project_name-multiqc.html)
>     project_name=$(echo $multiqc_html_name | rev | cut -f2-3 -d "-" | rev)
> ```

I think:

`project_name=${multiqc_html_name%"-multiqc.html"}`

is a more readable way to do this.  See the info at https://tldp.org/LDP/abs/html/parameter-substitution.html for more info on parameter expansion.  

% Removes from $var the shortest part of $Pattern that matches the back end of $var.

I'll leave it to you whether you want to change this.

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: all files reviewed, 2 unresolved discussions (waiting on @natashapinto and @RachelDuffin)

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith and @natashapinto)

___
*[src/code.sh, line 51 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11#-MMUwGm3B5ojR0--PFwh:-MMV1J3oEkV0Ft6s9y3Q:b1c52lg) ([raw file](https://github.com/moka-guys/dnanexus_upload_multiqc/blob/b21216b7a2dc055f1c997fe0db9c2ac48884217a/src/code.sh#L51)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I think:

`project_name=${multiqc_html_name%"-multiqc.html"}`

is a more readable way to do this.  See the info at https://tldp.org/LDP/abs/html/parameter-substitution.html for more info on parameter expansion.  

% Removes from $var the shortest part of $Pattern that matches the back end of $var.

I'll leave it to you whether you want to change this.
</blockquote></details>

Think I will leave as is as testing wasn't particularly straightforward.

**Review by Graeme-Smith — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_upload_multiqc/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
